services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: cartracker
    networks:
      - cartracker

  backend:
    build: ./backend
    ports:
      - "8000:8000"  # всередині мережі для npm
    depends_on:
      - db
    volumes:
      - ./frontend:/frontend
    environment:
      DATABASE_URL: postgresql://user:pass@db/cartracker
    networks:
      - cartracker

  npm:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - "80:80"    # HTTP
      - "81:81"    # адмінка NPM
      - "443:443"  # HTTPS
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
    networks:
      - cartracker

networks:
  cartracker:
    driver: bridge