services:
  # db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #   networks:
  #     - cartracker

  backend:
    build: ./backend
    expose:
      - "8000" # Only inside network
    depends_on:
      - db
    volumes:
      - ./frontend:/frontend
    networks:
      - cartracker

  npm:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - "80:80"    # HTTP
      - "81:81"    # Admin panel of NPM
      - "443:443"  # HTTPS
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
    networks:
      - cartracker

networks:
  cartracker:
    driver: bridge